name: "Swifty360Player CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  iOS_15_4:
    name: Xcode 13.2.1
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=15.2,name=iPhone 13 Pro"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -workspace "Swifty360Player.xcworkspace" -scheme "Swifty360Player" -destination "${{ matrix.destination }}" clean test | xcpretty
  iOS_14_4:
    name: Xcode 12.4
    runs-on: macos-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=14.4,name=iPhone 12 Pro"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -workspace "Swifty360Player.xcworkspace" -scheme "Swifty360Player" -destination "${{ matrix.destination }}" clean test | xcpretty
  iOS_13_7:
    name: Xcode 11.7
    runs-on: macos-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.7,name=iPhone 11"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -workspace "Swifty360Player.xcworkspace" -scheme "Swifty360Player" -destination "${{ matrix.destination }}" clean test | xcpretty
